module.exports = {
  publicRuntimeConfig: {
      API_BASE_URL_PRODUCT_SERVICE: process.env.API_BASE_URL_PRODUCT_SERVICE,
      API_BASE_URL_USER_SERVICE: process.env.API_BASE_URL_USER_SERVICE,
      API_BASE_URL_ORDER_SERVICE: process.env.API_BASE_URL_ORDER_SERVICE,
      WEBSITE_URL: process.env.WEBSITE_URL,
      MAIN_WEBSITE_URL: process.env.MAIN_WEBSITE_URL,
      WEBSITE_NAME: process.env.WEBSITE_NAME,
      WEBSITE_TAGLINE: process.env.WEBSITE_TAGLINE,
      WEBSITE_IMAGE_URL: process.env.WEBSITE_IMAGE_URL,
      NEXT_TELEMETRY_DISABLED: process.env.NEXT_TELEMETRY_DISABLED
  },
}
